//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM_CUSTEIO_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.ProdutoMaterial = new HashSet<ProdutoMaterial>();
        }
    
        public int Id { get; set; }
        public string Nome_Material { get; set; }
        public string Descricao { get; set; }
        public decimal Preco_produto { get; set; }
    
        public virtual ICollection<ProdutoMaterial> ProdutoMaterial { get; set; }
    }
}
