//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM_CUSTEIO_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutoMaterial
    {
        public int Id { get; set; }
        public int Produto_Id { get; set; }
        public int Material_Id { get; set; }
        public int QtdMaterial { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
